[workspace]
authors = ["Tyler Jost <tjost@bwh.harvard.edu>"]
channels = ["conda-forge", "bioconda", "r"]
name = "singlecell"
platforms = ["linux-64"]

version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.7"
scipy = ">=1.15.2,<2"
pandas = ">=2.2.3,<3"
numpy = ">=2.1.3,<3"
scikit-learn = ">=1.6.1,<2"
matplotlib = ">=3.10.0,<4"
jupyter = ">=1.1.1,<2"

scanpy = ">=1.9.8"
ipywidgets = ">=8.1.2"
pyyaml = ">=6.0.1"
leidenalg = ">=0.10.2"
anndata2ri = ">=1.3.1,<2.0"
gseapy = ">=0.12.0"

rpy2 = ">=3.5.11,<3.6"
r-base = ">=4"

bioconductor-scdblfinder = ">=1.16.0"
bioconductor-singlecellexperiment = ">=1.24.0"
bioconductor-biocparallel = ">=1.36.0"
bioconductor-genomeinfodb = ">=1.38.1,<1.39"
bioconductor-scry = "*"

bioconductor-mast = "*"
r-lme4 = "*" # for mast

[pypi-dependencies]
ipykernel = "*"