[workspace]
authors = ["Tyler Jost <tjost@bwh.harvard.edu>"]
channels = ["conda-forge", "bioconda", "r"]
name = "singlecell"
platforms = ["linux-64", "osx-64"]

version = "0.1.0"

[tasks]
# https://github.com/prefix-dev/pixi/issues/1573
post-install = "PREFIX=$CONDA_PREFIX .bioconductor-genomeinfodbdata-post-link.sh"
[dependencies]
python = ">=3.12.7"
scipy = ">=1.15.2,<2"
pandas = ">=2.2.3,<3"
numpy = ">=2.1.3,<3"
scikit-learn = ">=1.6.1,<2"
matplotlib = ">=3.10.0,<4"
plotnine = "*"
jupyter = ">=1.1.1,<2"

scanpy = ">=1.9.8"
scirpy = "*"
ipywidgets = ">=8.1.2"
pyyaml = ">=6.0.1"
leidenalg = ">=0.10.2"
anndata2ri = ">=1.3.1,<2.0"
gseapy = ">=0.12.0"
celltypist = "*"

rpy2 = ">=3.5.11,<3.6"
r-base = ">=4"

bioconductor-biocparallel = ">=1.36.0"
bioconductor-genomeinfodb = ">=1.38.1,<1.39"
bioconductor-mast = "*"
bioconductor-scry = "*"
bioconductor-scdblfinder = ">=1.16.0"
bioconductor-singlecellexperiment = ">=1.24.0"

r-SoupX = "*"
r-lme4 = "*" # for mast
muon = ">=0.1.7,<0.2"

[pypi-dependencies]
ipykernel = "*"
